### ISSUE TITLE
redminelib.exceptions.ResourceAttrError: Resource doesn't have the requested attribute

### ISSUE THREAD

**Issue by krozbol100** [wpoely86/redmine-azure-devops-migrate#1]
Hi,

thank you for this great contribution.

I'd like to ask you for a help, if you find some time.

I have python 3.9.1 installed. I use windows 10 vm. Installed requirements.txt. Edited migrate.py (with my redmine and azure devops info). Didn't change filtering options.

When I run it, it migrates couple of issues, along with comments (which is cool) but then it breaks with this:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\redmine\redmine-azure-devops-migrate\migrate.py", line 245, in <module>
    main()
  File "C:\Users\User\Desktop\redmine\redmine-azure-devops-migrate\migrate.py", line 189, in main
    create_work_item(work_client, issue)
  File "C:\Users\User\Desktop\redmine\redmine-azure-devops-migrate\migrate.py", line 125, in create_work_item
    if not note.notes:
  File "C:\Python39\lib\site-packages\redminelib\resources\base.py", line 197, in __getattr__
    raise exceptions.ResourceAttrError
redminelib.exceptions.ResourceAttrError: Resource doesn't have the requested attribute

When I change filtering to narrow the scope, it fails on some other issue. Seems like there is a problem with detecting parent issue, but i'm not that good in python to go around it.

Can you please take a look and perhaps give some advice?

Also, when I narrow the scope so much to have couple of good issues to migrate, it goes ok until it produces another error at the end:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\redmine\redmine-azure-devops-migrate\migrate.py", line 245, in <module>
    main()
  File "C:\Users\User\Desktop\redmine\redmine-azure-devops-migrate\migrate.py", line 192, in main
    with open(f"issue-mapping-{datetime.datetime.now().isoformat()}.json", "w") as json_out:
OSError: [Errno 22] Invalid argument: 'issue-mapping-2021-01-28T20:36:16.915698.json'

Thanks and br,
Sadmir.

**Comment by wpoely86** [comment]
I've pushed two commits, can you try again?

The second issue is probably because of the `:` in the name. I only used it on Linux. It now uses a name like `YYYYMMDD_HHMMSS`.

The first issue is a bit more puzzling. You get a 'note' from a issue without a 'notes' field. In all my testing, this was always the case. Which version of python-redmine are you using? I've changed it to use `getattr` as a test instead.

**Comment by krozbol100** [comment]
Sure, I'm running it again. So far, I don't see a "note without notes" issue (last run is still going for at least couple of hundreds issues). But I'll let you know if both previous problems were solved.

I also run this in CentOs, just to be sure that there is not Windows related problems.

In the meantime, I've got another error:

Adding link: 50531 -> 50617
Traceback (most recent call last):
  File "migrate.py", line 245, in <module>
    main()
  File "migrate.py", line 200, in main
    parent_link = Link(rel="System.LinkTypes.Hierarchy-Reverse", url=issue_map[issue.parent.id][1])
KeyError: 50531

Can you please take a look at this one? This one is occurring on all my recent runs (it seems that there is a new redmine issue which I got with a query >=2021-01-01).

Thanks and br,
Sadmir.

Edit: You can disregard this issue: my last run was with issues from 2017 and I didn't get the problem with adding a link.

Also, last run imported all issues with comments, without errors about "note without notes" and also produced a json file.

**Comment by wpoely86** [comment]
That seems like a case where the parent is not migrated to Azure DevOps (redmine issue 50531 in this case)?

I've pushed a commit to skip those case.

**Comment by krozbol100** [comment]
Great, thank you. I'll close this now (but I have another question for you, if you don't mind, and I'll open another issue)
